### ISSUE TITLE
Playing status is not synced over clients on launch

### ISSUE THREAD

**Issue by PureTryOut** [MayaPosch/NymphCast#77]
I have a client running on my phone (client 1, on postmarketOS) and on my laptop (client 2, on Alpine Linux). The server is running on the same device as client 2 is.

Client 2 is playing a local file on the server, this works as expected. However client 1 does not show this, it's as if nothing is playing at all yet. Only when I click the play button once (and then ignore the warning about no file being added yet) does it sync playing status. When this has happened any playback state change (pause, resume, etc) are synced just fine over these clients.

**Comment by MayaPosch** [comment]
Is client 1 in this scenario connected to the server instance?

**Comment by PureTryOut** [comment]
Yes both are.

**Comment by MayaPosch** [comment]
I think that UX-related confusion may be the problem here. Upon starting NymphCast Player a remote server (if any are available) is currently listed in the dropdown box, but until an action is performed, the player will not be connected to this remote. This action can include selecting a remote in the dropdown box, even the top entry that was already shown (but not yet connected).

A possible fix would be to only show a remote in the dropbox box when the player is connected to it.

**Comment by PureTryOut** [comment]
Ah yeah that indeed seems like UX-confusion then. Indeed, only showing a selected entry in the dropdown when you're actually connected seems like a good solution for this.

**Comment by MayaPosch** [comment]
I have modified the behaviour of the combobox to not show a remote upon refreshing the list.

This used to be the old behaviour, but I think I removed it a while ago because of problems on Android. That should be verified again, but at least under Windows it seems to work as intended.

**Comment by PureTryOut** [comment]
Thanks! Any chance you could tag a new release btw? The 0.1 version was almost a year ago now :wink:

**Comment by MayaPosch** [comment]
I'll tag a new pre-release (v0.2-alpha0) as soon as all major issue tickets have been resolved :)
